---
title: "tabdif Vignette"
author: "[David Montaner](http://www.dmontaner.com)"
created: 2017-02-27
modified: 2017-02-27
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tabdif Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, results = "hide"}
options (width = 80)
library (datasets)
```

About
--------------------------------------------------------------------------------

The `tabdif` library is devised to find differences between two tables (data.fames).
This is usefull for instance when you want to find changes between two versions of the same dataset.

The function `compareDataFrames` creates a list of class `dfcomp` containing the following information about the differences:

- __Deleted Columns__:           Column names in the first (_old_) data.frame not found in the second (_new_) data.frame.
- __New Columns__:               Column names in the second        data.frame not found in the first          data.frame.
- __Changed Column Classes__:    Columns with different class in the first and second data.frames.
- __Duplicated Rows Old Table__: Rows with duplicated IDs in the first  data.frame. This rows are not compared.
- __Duplicated Rows New Table__: Rows with duplicated IDs in the second data.frame. This rows are not compared.
- __Deleted Rows__:              Rows in the first  data.frame which ID is not found in the second data.frame.
- __New Rows__:                  Rows in the second data.frame which ID is not found in the first  data.frame.
- __Changed Cells__:             Cells which have changed from one dataset to the other.

One or several columns which have to be common in both datasets are used as _row keys_;
together with the other columns names they should uniquely identify cells for the comparison to be done. 

Example Data
--------------------------------------------------------------------------------

Imagine we have two similar data.frames `iris0` and `iris1`

```{r}
iris0 <- iris1 <- cbind (iris, N = 1:50)

## with some some cell differences
iris1[4, 1] <- 80
iris1[5, 2] <- 90
iris1[6, 3:4] <- 100 

## with some different rows
iris0 <- iris0[-(1:3),]
iris1 <- iris1[-150]

## with some different columns
iris0[,"mycol0"] <- "A"
iris1[,c ("mycol1", "mycol2")] <- "B"

## with some duplicated rows
iris0 <- rbind (iris0, iris0[10,])
iris1 <- rbind (iris1, iris1[20:21,])
```

```{r}
head (iris0)
head (iris1)
```

Usage
--------------------------------------------------------------------------------

The function `compareDataFrames` finds the differences between the two tables.
In our example _row keys_ are defined by 2 columns: "N" and "Species".

```{r}
library (tabdif)
dif <- compareDataFrames (iris0, iris1, rowKeys = c ("N", "Species"))
summary (dif)
```

The elements of the `dfcomp` list created by `compareDataFrames` 
resume the differences between our two tables.
For instance `dif$dif.cells` indicates the cells which have changed.

```{r}
dif$dif.cells
```


Export
--------------------------------------------------------------------------------

The `dfcomp` list can easily be exported to an _xlsx_ file. 
Each element of the list will be in a separated sheet of the _xlsx_ file,
including a summary of the differences in the first page. 

```{r}
dfcomp2xlsx (dif, file = "dif_report.xlsx")
```

```{r, echo = FALSE, results = "hide"}
unlink ("dif_report.xlsx")
```
